### PR TITLE
Graw DFM check

### PR DESCRIPTION
**Pull request by LukePrior**

### CODE REVIEW

**Comment by oh3bsg** [comment]
When I trace DFM09 sonde data, I notice that serial number what I sent to sondehub was empty (""), and after DFM was sent serial number data that serial number field was filled. What I understand is that DFM decoder only fill that serial number field when it receive that. That "Dxxxxxxxx" is auto_rx feature. Or precisely dfm09mod.c in auto_rx is filled that by default.

**Comment by LukePrior** [comment]
Ahh ok, I will make some changes to check that serial is not "".

**Comment by oh3bsg** [comment]
I fixed that allready

**Comment by LukePrior** [comment]
Ok

**Pull request closed without merging**
